class PrefName

  def self.get_pref_name(pref_id)
    case pref_id
    when '1' then
      pref_name = '北海道'
    when '2' then
      pref_name = '青森県'
    when '3' then
      pref_name = '岩手県'
    when '4' then
      pref_name = '宮城県'
    when '5' then
      pref_name = '秋田県'
    when '6' then
      pref_name = '山形県'
    when '7' then
      pref_name = '福島県'
    when '8' then
      pref_name = '茨城県'
    when '9' then
      pref_name = '栃木県'
    when '10' then
      pref_name = '群馬県'
    when '11' then
      pref_name = '埼玉県'
    when '12' then
      pref_name = '千葉県'
    when '13' then
      pref_name = '東京都'
    when '14' then
      pref_name = '神奈川県'
    when '15' then
      pref_name = '新潟県'
    when '16' then
      pref_name = '富山県'
    when '17' then
      pref_name = '石川県'
    when '18' then
      pref_name = '福井県'
    when '19' then
      pref_name = '山梨県'
    when '20' then
      pref_name = '長野県'
    when '21' then
      pref_name = '岐阜県'
    when '22' then
      pref_name = '静岡県'
    when '23' then
      pref_name = '愛知県'
    when '24' then
      pref_name = '三重県'
    when '25' then
      pref_name = '滋賀県'
    when '26' then
      pref_name = '京都府'
    when '27' then
      pref_name = '大阪府'
    when '28' then
      pref_name = '兵庫県'
    when '29' then
      pref_name = '奈良県'
    when '30' then
      pref_name = '和歌山県'
    when '31' then
      pref_name = '鳥取県'
    when '32' then
      pref_name = '島根県'
    when '33' then
      pref_name = '岡山県'
    when '34' then
      pref_name = '広島県'
    when '35' then
      pref_name = '山口県'
    when '36' then
      pref_name = '徳島県'
    when '37' then
      pref_name = '香川県'
    when '38' then
      pref_name = '愛媛県'
    when '39' then
      pref_name = '高知県'
    when '40' then
      pref_name = '福岡県'
    when '41' then
      pref_name = '佐賀県'
    when '42' then
      pref_name = '長崎県'
    when '43' then
      pref_name = '熊本県'
    when '44' then
      pref_name = '大分県'
    when '45' then
      pref_name = '宮崎県'
    when '46' then
      pref_name = '鹿児島県'
    else
      pref_name = '沖縄県'
    end
        
  end
end
